imports:
    - { resource: config_dev.yml }

parameters:
    test_username: testuser
    test_password: testpassword

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

doctrine:
    dbal:
        dbname: "%test_database_name%"
        user: "%test_database_user%"
        password: "%test_database_password%"

security:
    firewalls:
        api:
            http_basic: ~
            fos_oauth: false
            provider: in_memory
    providers:
        in_memory:
            memory:
                users:
                    %test_username%: { password: "%test_password%", roles: [ 'ROLE_ADMIN' ] }

liip_functional_test:
    authentication:
        username: "%test_username%"
        password: "%test_password%"

