# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        stateless:
            pattern: ^/(_(profiler|wdt)|monitor|css|images|js)
            security: false
        basic_auth:
            pattern: ^/doc
            http_basic: ~
            stateless:  true
        oauth_token:
            pattern: ^/oauth/v2/token
            security: false
        api:
            pattern:   ^/
            fos_oauth: true
            stateless: true
            anonymous: false

    access_control:
        - { path: ^/oauth/v2/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
